### ISSUE TITLE
"error: infinite recursion encountered" after following User's Guide

### ISSUE THREAD

**Issue by epall** [NixOS/nixops#284]
I am completely new to nix, having been introduced to it at Domen's talk at PyCon last week. Today I tried to set up a Linux guest on my OS X host using NixOps + VirtualBox, but I ran into some difficulty that's way over my head. I'm not sure whether I'm doing something wrong, the docs are outdated, or I've actually found a bug. 

I installed the Nix package manager onto my OS X 10.9.5 system using the curl script at http://nixos.org/nix/. It seems to be working fine, and I'm able to install various packages on the OS X host.

Today I tried to follow the NixOps User's Guide at http://hydra.nixos.org/build/21432503/download/1/manual/manual.html#idm140737319353616 to set up a VirtualBox guest running NixOS, but I ran into difficulty almost immediately. After creating the network and trying to get the info about it, I was confronted with "error: infinite recursion encountered". I've pasted my console session at http://hastebin.com/raw/iqakozegew with the results of `nixops info -d trivial --show-trace`, among other things.

Did I do something wrong in following the User's Guide, or is something out of date?

**Comment by epall** [comment]
I'm guessing this is related to #281, but in my case I'm trying to deploy to virtualbox, which he says is working fine in his configuration.

**Comment by statusfailed** [comment]
I'm also having this exact issue, but my host OS is NixOS. I have only tried to follow the manual in setting up a virtualbox machine, which fails with the same "error: infinite recursion encountered" error.

**Comment by copumpkin** [comment]
Perhaps @nbp knows more? He's my go-to these days for infinite recursion advice :smile:

**Comment by rbvermaa** [comment]
Can you please let us know what version of nixops you are using, and which nixpkgs channel?

**Comment by statusfailed** [comment]
Nixops version and nixpkgs channel:

    > nixops --version
    NixOps 1.2
    > nix-channel --list
    nixos https://nixos.org/channels/nixos-unstable

let me know if I can give any other info to help!

**Comment by jamesthompson** [comment]
I'm seeing exactly the same errors after following the nixops manual with exactly the same nixops --version and nix channel as @statusfailed.

It looks like something's going wrong with the hetzner.nix expression perhaps?

**Comment by rbvermaa** [comment]
OK, I have looked into this and have come a bit closer to seeing what is happening. Seems that changes in the  NixOS module system prevents strict evaluation of the NixOS option, which is what nixops is doing to getting the option values:

    [nix-shell:~/src/nixops]$ nix-instantiate -A info.resources.gceImages.bootstrap --arg networkExprs '[ ./examples/trivial-gce.nix ]' nix/eval-machine-info.nix  --argstr uuid asd --arg args '[]' --eval-only  -I nixpkgs=../nixpkgs 
    { _module = <CODE>; _name = <CODE>; _type = <CODE>; accessKey = <CODE>; description = <CODE>; name = <CODE>; project = <CODE>; serviceAccount = <CODE>; sourceUri = <CODE>; }

    [nix-shell:~/src/nixops]$ nix-instantiate  --arg networkExprs '[ ./examples/trivial-gce.nix ]' nix/eval-machine-info.nix  --argstr uuid asd --arg args '[]' --eval-only  -I nixpkgs=../nixpkgs  -A info.resources.gceImages.bootstrap._module.args
    { name = <CODE>; nodes = <CODE>; pkgs = <CODE>; resources = <CODE>; uuid = <CODE>; }

**Comment by rbvermaa** [comment]
Could you see if the commit I just pushed fixes the issue for you. I am not that familiar with the NixOS module system internals, but I think this change should at least work around the issue until we know more.

**Comment by jamesthompson** [comment]
@rbvermaa I just checked this on my Darwin machine with the [latest unstable build](http://hydra.nixos.org/build/21814005). It's happily building the VirtualBox instance now from the basic nixops manual demonstration trivial expression. Fingers crossed it will work ok for EC2 etc. Thanks very much for your help!!

**Comment by statusfailed** [comment]
I'm looking [here](http://hydra.nixos.org/eval/1192293), which suggests the x86_64 (not Darwin) build failed? I don't know how to install it other than with nix-env. Here's what I'm trying:

    > nix-env -i nixops-1.3pre1472_af77653
    warning: name collision in input Nix expressions, skipping ‘/home/sf/.nix-defexpr/channels_root/nixos’
    error: selector ‘nixops-1.3pre1472_af77653’ matches no derivations

I'm not sure what to do now.

**Comment by statusfailed** [comment]
warning: I have no idea how correct the following is.

The [x86_64 build](http://hydra.nixos.org/build/21814003) is still failing, because "A dependency of the build failed".

Finding the log of the failed dependency build ([here](http://hydra.nixos.org/build/21814003/nixlog/1)) yields this line, from a unit test:

    AssertionError: test_callback_response did not run within two microseconds

It sounds like the particular test is nondeterministic (because a particularly slowly-running machine might take a long time to run it). Hydra also says that build is cached, which presumably means it hasn't been tried again.

I would really like to fix this, because right now I can't use NixOps *at all*.

**Comment by rbvermaa** [comment]
@statusfailed Can you build from source (nix-build -A build.x86_64-linux release.nix from top of cloned repo)? I will disable the httpretty test in the meanwhile.

**Comment by statusfailed** [comment]
I ran that command from within the cloned repo of nixops, but I got lots of messages like "File format not recognised". I've included the last few lines of output.
Apologies if I've done something wrong, I'm pretty new to Nix/NixOS/NixOps

    strip:/nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/lib/python2.7/site-packages/nixops-1.3pre0_abcdef-py2.7.egg-info/dependency_links.txt: File truncated
    strip:/nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/lib/python2.7/site-packages/nixops-1.3pre0_abcdef-py2.7.egg-info/SOURCES.txt: File format not recognized
    strip:/nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/bin/.nixops-wrapped: File format not recognized
    strip:/nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/bin/nixops: File format not recognized
    patching script interpreter paths in /nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef
    /nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/bin/.nixops-wrapped
    wrapping `/nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef/bin/.nixops-wrapped'...
    /nix/store/a8r38i7ql6hhiar3pvx9zc58p7xvlmby-nixops-1.3pre0_abcdef

**Comment by rbvermaa** [comment]
This log suggests it succeded. There should be a result/ directory with the resulting build. You can also install the build in your user environment by running: nix-env -iA build.x86_64-linux -f release.nix

**Comment by statusfailed** [comment]
Great, thank you! That worked perfectly. I am no longer getting the "infinite recursion" error from the commands in the manual.

Thanks again!

**Comment by MasseGuillaume** [comment]
@epall look like it works now:

```
git clone git@github.com:NixOS/nixops.git
cd nixops
git checkout 5c7663dfe1e2af9c0396c5c86d995452ef2efc8a
nix-build release.nix -A build.x86_64-darwin
nix-env -i /nix/store/vb4ccadxj0iyx90sb7wmzrf5f0bm24dw-nixops-1.3pre0_abcdef

Guillaumes-MacBook-Pro:VM_via_nixops masgui$ nixops create ./trivial.nix ./trivial-vbox.nix -d trivial
created deployment ‘e94e52c7-0b74-11e5-8b3c-ac87a3111724’
e94e52c7-0b74-11e5-8b3c-ac87a3111724
Guillaumes-MacBook-Pro:VM_via_nixops masgui$ nixops deploy -d trivial
webserver> creating VirtualBox VM...
webserver> Virtual machine 'nixops-e94e52c7-0b74-11e5-8b3c-ac87a3111724-webserver' is created and registered.
webserver> UUID: 49d3b620-8ccc-43cc-a8a3-f4794353e6e0
webserver> Settings file: '/Users/masgui/VirtualBox VMs/nixops-e94e52c7-0b74-11e5-8b3c-ac87a3111724-webserver/nixops-e94e52c7-0b74-11e5-8b3c-ac87a3111724-webserver.vbox'
webserver> creating disk ‘disk1’...
webserver> these derivations will be built:
webserver>   /nix/store/nwvnqgjvysgz9m22gj5rczxajmd6gzih-virtualbox-nixops-14.12.231.139ead2.vdi.xz.drv
webserver>   /nix/store/6kici7hi0n1l7z8lcbhd8h29002vyliz-virtualbox-nixops-14.12.231.139ead2.vdi.drv
webserver> building path(s) ‘/nix/store/ghxgnqh7jk5w8jslc7q396cvyzm62h2y-virtualbox-nixops-14.12.231.139ead2.vdi.xz’
webserver> 
webserver> trying http://nixos.org/releases/nixos/virtualbox-nixops-images/virtualbox-nixops-14.12.231.139ead2.vdi.xz
webserver>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
webserver>                                  Dload  Upload   Total   Spent    Left  Speed
100  172M  100  172M    0     0  3579k      0  0:00:49  0:00:49 --:--:-- 5147k
webserver> building path(s) ‘/nix/store/8yk38y63n4n5dmr685vx3x9vs376mqqv-virtualbox-nixops-14.12.231.139ead2.vdi’
webserver> 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
webserver> Clone hard disk created in format 'VDI'. UUID: 92a5b144-88c9-450a-a0c4-cdeae585d16f
webserver> attaching disk ‘disk1’...
webserver> Waiting for VM "nixops-e94e52c7-0b74-11e5-8b3c-ac87a3111724-webserver" to power on...
webserver> VM "nixops-e94e52c7-0b74-11e5-8b3c-ac87a3111724-webserver" has been successfully started.
```

**Comment by epall** [comment]
Confirmed! Works for me, as well, with nixops-1.3pre1489_6c3b875

**Comment by anderspapitto** [comment]
as a note to anyone else who may still be seeing this - the fix is currently reflected in the nixopsUnstable package, but not the nixops package (in the unstable nixpkgs channel)

**Comment by FlorianHeigl** [comment]
@anderspapitto thanks, I also just hit this wall, thinking I'd be better off with a -stable env :)
